import type { SeedProduct } from "@/lib/catalog/seed-product";

/** Newfangled Audio — Eventide sub-brand; split from EVENTIDE_PRODUCTS. */
export const NEWFANGLED_AUDIO_PRODUCTS: SeedProduct[] = [
  {
    name: "Articulate",
    slug: "articulate",
    canonicalId: "articulate-eventide",
    image: "/images/products/eventide/articulate.webp",
    category: "Effects",
    manufacturer: "Newfangled Audio",
    registeredPrice: 69,
    tags: ["newfangled-audio", "effects"],
    retailers: ["plugin-boutique", "gear4music"],
  },
  {
    name: "Elevate Mastering Bundle",
    slug: "elevate-mastering-bundle",
    canonicalId: "elevate-mastering-bundle-newfangled-audio",
    image: "/images/products/eventide/elevate-mastering-bundle.webp",
    category: "Limiter",
    manufacturer: "Newfangled Audio",
    registeredPrice: 199,
    tags: ["newfangled-audio", "bundle", "mastering"],
    retailers: ["plugin-boutique", "gear4music"],
  },
  {
    name: "EQuivocate",
    slug: "equivocate",
    canonicalId: "equivocate-eventide",
    image: "/images/products/eventide/equivocate.webp",
    category: "Equalizer",
    manufacturer: "Newfangled Audio",
    registeredPrice: 99,
    tags: ["newfangled-audio", "equalizer"],
    retailers: ["plugin-boutique", "gear4music"],
  },
  {
    name: "Fixate:Midrange",
    slug: "fixate-midrange",
    canonicalId: "fixate-midrange-eventide",
    image: "/images/products/eventide/fixate-midrange.webp",
    category: "Effects",
    manufacturer: "Newfangled Audio",
    registeredPrice: 139,
    tags: ["newfangled-audio", "effects"],
    retailers: ["plugin-boutique", "gear4music"],
  },
  {
    name: "Generate",
    slug: "generate",
    canonicalId: "generate-eventide",
    image: "/images/products/eventide/generate.webp",
    category: "Effects",
    manufacturer: "Newfangled Audio",
    registeredPrice: 99,
    tags: ["newfangled-audio", "effects"],
    retailers: ["plugin-boutique", "gear4music"],
  },
  {
    name: "Invigorate",
    slug: "invigorate",
    canonicalId: "invigorate-eventide",
    image: "/images/products/eventide/invigorate.webp",
    category: "Effects",
    manufacturer: "Newfangled Audio",
    registeredPrice: 99,
    tags: ["newfangled-audio", "effects"],
    retailers: ["plugin-boutique", "gear4music"],
  },
  {
    name: "Punctuate",
    slug: "punctuate",
    canonicalId: "punctuate-eventide",
    image: "/images/products/eventide/punctuate.webp",
    category: "Effects",
    manufacturer: "Newfangled Audio",
    registeredPrice: 99,
    tags: ["newfangled-audio", "effects"],
    retailers: ["plugin-boutique", "gear4music"],
  },
  {
    name: "Recirculate",
    slug: "recirculate",
    canonicalId: "recirculate-eventide",
    image: "/images/products/eventide/recirculate.webp",
    category: "Effects",
    manufacturer: "Newfangled Audio",
    registeredPrice: 99,
    tags: ["newfangled-audio", "effects"],
    retailers: ["plugin-boutique", "gear4music"],
  },
  {
    name: "Saturate",
    slug: "saturate",
    canonicalId: "saturate-eventide",
    image: "/images/products/eventide/saturate.webp",
    category: "Saturation",
    manufacturer: "Newfangled Audio",
    registeredPrice: 49,
    tags: ["newfangled-audio", "saturation"],
    retailers: ["plugin-boutique", "gear4music"],
  },
];
